
package org.fosstrak.ale.wsdl.aletm.epcglobal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import org.fosstrak.ale.wsdl.aletm.epcglobal.ALETMServicePortType;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Apr 16 14:42:07 KST 2010
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebServiceClient(name = "ALETMService", targetNamespace = "urn:epcglobal:aletm:wsdl:1", wsdlLocation = "file:/C:/Documents and Settings/Auto-ID Lab Team/My Documents/ALE middleware source/workspace/fc-commons/src/main/resources/wsdl/EPCglobal-ale-1_1-aletm.wsdl")
public class ALETMService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:epcglobal:aletm:wsdl:1", "ALETMService");
    public final static QName ALETMServicePort = new QName("urn:epcglobal:aletm:wsdl:1", "ALETMServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Documents and Settings/Auto-ID Lab Team/My Documents/ALE middleware source/workspace/fc-commons/src/main/resources/wsdl/EPCglobal-ale-1_1-aletm.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/Documents and Settings/Auto-ID Lab Team/My Documents/ALE middleware source/workspace/fc-commons/src/main/resources/wsdl/EPCglobal-ale-1_1-aletm.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ALETMService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ALETMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ALETMService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ALETMServicePort
     */
    @WebEndpoint(name = "ALETMServicePort")
    public ALETMServicePortType getALETMServicePort() {
        return (ALETMServicePortType)super.getPort(ALETMServicePort, ALETMServicePortType.class);
    }

}
