
package org.fosstrak.ale.wsdl.aletm.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Apr 16 14:42:07 KST 2010
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "SecurityException", targetNamespace = "urn:epcglobal:aletm:wsdl:1")

public class SecurityExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100416144207L;
    
    private org.fosstrak.ale.wsdl.aletm.epcglobal.SecurityException securityException;

    public SecurityExceptionResponse() {
        super();
    }
    
    public SecurityExceptionResponse(String message) {
        super(message);
    }
    
    public SecurityExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SecurityExceptionResponse(String message, org.fosstrak.ale.wsdl.aletm.epcglobal.SecurityException securityException) {
        super(message);
        this.securityException = securityException;
    }

    public SecurityExceptionResponse(String message, org.fosstrak.ale.wsdl.aletm.epcglobal.SecurityException securityException, Throwable cause) {
        super(message, cause);
        this.securityException = securityException;
    }

    public org.fosstrak.ale.wsdl.aletm.epcglobal.SecurityException getFaultInfo() {
        return this.securityException;
    }
}
