
package org.fosstrak.ale.wsdl.aletm.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Apr 16 14:42:07 KST 2010
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "TMSpecValidationException", targetNamespace = "urn:epcglobal:aletm:wsdl:1")

public class TMSpecValidationExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100416144207L;
    
    private org.fosstrak.ale.wsdl.aletm.epcglobal.TMSpecValidationException tmSpecValidationException;

    public TMSpecValidationExceptionResponse() {
        super();
    }
    
    public TMSpecValidationExceptionResponse(String message) {
        super(message);
    }
    
    public TMSpecValidationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public TMSpecValidationExceptionResponse(String message, org.fosstrak.ale.wsdl.aletm.epcglobal.TMSpecValidationException tmSpecValidationException) {
        super(message);
        this.tmSpecValidationException = tmSpecValidationException;
    }

    public TMSpecValidationExceptionResponse(String message, org.fosstrak.ale.wsdl.aletm.epcglobal.TMSpecValidationException tmSpecValidationException, Throwable cause) {
        super(message, cause);
        this.tmSpecValidationException = tmSpecValidationException;
    }

    public org.fosstrak.ale.wsdl.aletm.epcglobal.TMSpecValidationException getFaultInfo() {
        return this.tmSpecValidationException;
    }
}
