
package org.fosstrak.ale.wsdl.ale.epcglobal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Apr 16 14:42:02 KST 2010
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebService(targetNamespace = "urn:epcglobal:ale:wsdl:1", name = "ALEServicePortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface ALEServicePortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "VoidHolder", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "undefineReturn")
    @WebMethod
    public org.fosstrak.ale.wsdl.ale.epcglobal.VoidHolder undefine(
        @WebParam(partName = "parms", name = "Undefine", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        Undefine parms
    ) throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, SecurityExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetECSpecNamesResult", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "getECSpecNamesReturn")
    @WebMethod
    public org.fosstrak.ale.wsdl.ale.epcglobal.ArrayOfString getECSpecNames(
        @WebParam(partName = "parms", name = "GetECSpecNames", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        EmptyParms parms
    ) throws ImplementationExceptionResponse, SecurityExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ImmediateResult", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "immediateReturn")
    @WebMethod
    public org.fosstrak.ale.xsd.ale.epcglobal.ECReports immediate(
        @WebParam(partName = "parms", name = "Immediate", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        Immediate parms
    ) throws ImplementationExceptionResponse, SecurityExceptionResponse, ECSpecValidationExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "VoidHolder", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "defineReturn")
    @WebMethod
    public org.fosstrak.ale.wsdl.ale.epcglobal.VoidHolder define(
        @WebParam(partName = "parms", name = "Define", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        Define parms
    ) throws ImplementationExceptionResponse, SecurityExceptionResponse, ECSpecValidationExceptionResponse, DuplicateNameExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "VoidHolder", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "unsubscribeReturn")
    @WebMethod
    public org.fosstrak.ale.wsdl.ale.epcglobal.VoidHolder unsubscribe(
        @WebParam(partName = "parms", name = "Unsubscribe", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        Unsubscribe parms
    ) throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, NoSuchSubscriberExceptionResponse, SecurityExceptionResponse, InvalidURIExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetECSpecResult", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "getECSpecReturn")
    @WebMethod
    public org.fosstrak.ale.xsd.ale.epcglobal.ECSpec getECSpec(
        @WebParam(partName = "parms", name = "GetECSpec", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        GetECSpec parms
    ) throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, SecurityExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetVendorVersionResult", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "getVendorVersionReturn")
    @WebMethod
    public java.lang.String getVendorVersion(
        @WebParam(partName = "parms", name = "GetVendorVersion", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        EmptyParms parms
    ) throws ImplementationExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetSubscribersResult", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "getSubscribersReturn")
    @WebMethod
    public org.fosstrak.ale.wsdl.ale.epcglobal.ArrayOfString getSubscribers(
        @WebParam(partName = "parms", name = "GetSubscribers", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        GetSubscribers parms
    ) throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, SecurityExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "PollResult", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "pollReturn")
    @WebMethod
    public org.fosstrak.ale.xsd.ale.epcglobal.ECReports poll(
        @WebParam(partName = "parms", name = "Poll", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        Poll parms
    ) throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, SecurityExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetStandardVersionResult", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "getStandardVersionReturn")
    @WebMethod
    public java.lang.String getStandardVersion(
        @WebParam(partName = "parms", name = "GetStandardVersion", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        EmptyParms parms
    ) throws ImplementationExceptionResponse;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "VoidHolder", targetNamespace = "urn:epcglobal:ale:wsdl:1", partName = "subscribeReturn")
    @WebMethod
    public org.fosstrak.ale.wsdl.ale.epcglobal.VoidHolder subscribe(
        @WebParam(partName = "parms", name = "Subscribe", targetNamespace = "urn:epcglobal:ale:wsdl:1")
        Subscribe parms
    ) throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, DuplicateSubscriptionExceptionResponse, SecurityExceptionResponse, InvalidURIExceptionResponse;
}
