
package org.fosstrak.ale.wsdl.ale.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Apr 16 14:42:02 KST 2010
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "DuplicateSubscriptionException", targetNamespace = "urn:epcglobal:ale:wsdl:1")

public class DuplicateSubscriptionExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100416144202L;
    
    private org.fosstrak.ale.wsdl.ale.epcglobal.DuplicateSubscriptionException duplicateSubscriptionException;

    public DuplicateSubscriptionExceptionResponse() {
        super();
    }
    
    public DuplicateSubscriptionExceptionResponse(String message) {
        super(message);
    }
    
    public DuplicateSubscriptionExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public DuplicateSubscriptionExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.DuplicateSubscriptionException duplicateSubscriptionException) {
        super(message);
        this.duplicateSubscriptionException = duplicateSubscriptionException;
    }

    public DuplicateSubscriptionExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.DuplicateSubscriptionException duplicateSubscriptionException, Throwable cause) {
        super(message, cause);
        this.duplicateSubscriptionException = duplicateSubscriptionException;
    }

    public org.fosstrak.ale.wsdl.ale.epcglobal.DuplicateSubscriptionException getFaultInfo() {
        return this.duplicateSubscriptionException;
    }
}
