
package org.fosstrak.ale.wsdl.ale.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Apr 16 14:42:02 KST 2010
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "DuplicateNameException", targetNamespace = "urn:epcglobal:ale:wsdl:1")

public class DuplicateNameExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100416144202L;
    
    private org.fosstrak.ale.wsdl.ale.epcglobal.DuplicateNameException duplicateNameException;

    public DuplicateNameExceptionResponse() {
        super();
    }
    
    public DuplicateNameExceptionResponse(String message) {
        super(message);
    }
    
    public DuplicateNameExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public DuplicateNameExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.DuplicateNameException duplicateNameException) {
        super(message);
        this.duplicateNameException = duplicateNameException;
    }

    public DuplicateNameExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.DuplicateNameException duplicateNameException, Throwable cause) {
        super(message, cause);
        this.duplicateNameException = duplicateNameException;
    }

    public org.fosstrak.ale.wsdl.ale.epcglobal.DuplicateNameException getFaultInfo() {
        return this.duplicateNameException;
    }
}
