
package org.fosstrak.ale.wsdl.ale.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Apr 16 14:42:01 KST 2010
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "ECSpecValidationException", targetNamespace = "urn:epcglobal:ale:wsdl:1")

public class ECSpecValidationExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100416144201L;
    
    private org.fosstrak.ale.wsdl.ale.epcglobal.ECSpecValidationException ecSpecValidationException;

    public ECSpecValidationExceptionResponse() {
        super();
    }
    
    public ECSpecValidationExceptionResponse(String message) {
        super(message);
    }
    
    public ECSpecValidationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ECSpecValidationExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.ECSpecValidationException ecSpecValidationException) {
        super(message);
        this.ecSpecValidationException = ecSpecValidationException;
    }

    public ECSpecValidationExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.ECSpecValidationException ecSpecValidationException, Throwable cause) {
        super(message, cause);
        this.ecSpecValidationException = ecSpecValidationException;
    }

    public org.fosstrak.ale.wsdl.ale.epcglobal.ECSpecValidationException getFaultInfo() {
        return this.ecSpecValidationException;
    }
}
