
package org.fosstrak.ale.wsdl.ale.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Apr 16 14:42:01 KST 2010
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "ImplementationException", targetNamespace = "urn:epcglobal:ale:wsdl:1")

public class ImplementationExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100416144201L;
    
    private org.fosstrak.ale.wsdl.ale.epcglobal.ImplementationException implementationException;

    public ImplementationExceptionResponse() {
        super();
    }
    
    public ImplementationExceptionResponse(String message) {
        super(message);
    }
    
    public ImplementationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImplementationExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.ImplementationException implementationException) {
        super(message);
        this.implementationException = implementationException;
    }

    public ImplementationExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.ImplementationException implementationException, Throwable cause) {
        super(message, cause);
        this.implementationException = implementationException;
    }

    public org.fosstrak.ale.wsdl.ale.epcglobal.ImplementationException getFaultInfo() {
        return this.implementationException;
    }
}
