
package org.fosstrak.ale.wsdl.ale.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Fri Apr 16 14:42:02 KST 2010
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "NoSuchSubscriberException", targetNamespace = "urn:epcglobal:ale:wsdl:1")

public class NoSuchSubscriberExceptionResponse extends Exception {
    public static final long serialVersionUID = 20100416144202L;
    
    private org.fosstrak.ale.wsdl.ale.epcglobal.NoSuchSubscriberException noSuchSubscriberException;

    public NoSuchSubscriberExceptionResponse() {
        super();
    }
    
    public NoSuchSubscriberExceptionResponse(String message) {
        super(message);
    }
    
    public NoSuchSubscriberExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchSubscriberExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.NoSuchSubscriberException noSuchSubscriberException) {
        super(message);
        this.noSuchSubscriberException = noSuchSubscriberException;
    }

    public NoSuchSubscriberExceptionResponse(String message, org.fosstrak.ale.wsdl.ale.epcglobal.NoSuchSubscriberException noSuchSubscriberException, Throwable cause) {
        super(message, cause);
        this.noSuchSubscriberException = noSuchSubscriberException;
    }

    public org.fosstrak.ale.wsdl.ale.epcglobal.NoSuchSubscriberException getFaultInfo() {
        return this.noSuchSubscriberException;
    }
}
